name: Sync Changes from Template
on: workflow_dispatch
  # schedule:
  #   # Run at 6:00 AM every two days
  #   - cron: "0 6 */2 * *"

jobs:
  sync-from-template:
    # don't run this job on the template
    if: github.repository != 'acm-ucr/hackathon-website'
    name: Sync changes from acm-ucr/hackathon-website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Fetch all
        working-directory: ${{ github.repository }}
        run: |
          git remote add template https://github.com/acm-ucr/hackathon-website
          git fetch --all

      - name: Checkout and push Template Dev Branch
        working-directory: ${{ github.repository }}
        run: |
          current_date=$(date '+%m/%d/%Y')
          branch_exists=$(git branch --list --remote | grep -F "origin/sync-template")
          if [ -z "$branch_exists" ]
          then
            git checkout -b sync-template template/dev
            git push origin sync-template
          else
            git checkout -b sync-template origin/sync-template
            git merge template/dev
            git commit -m "Merge changes from $current_date"
            git push origin sync-template
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update or Create Pull Request
        working-directory: ${{ github.repository }}
        run: |
          current_date=$(date '+%m/%d/%Y')
          pr_number=$(gh pr list --base dev --state open --json number --jq ".[] | select(.title == \"Sync Template Changes\") | .number")
          if [ -z "$pr_number" ]
          then
            gh pr create --base dev --head sync-template --title "Sync Template Changes" --body "Syncing template changes from $current_date"
          else
            gh pr update $pr_number --base dev --head sync-template --title "Sync Template Changes" --body "Syncing template changes from $current_date"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
